### PR TITLE
Allow redux 4

### PR DESCRIPTION
**Pull request by krzysiek1507**

### CODE REVIEW

**Comment by krzysiek1507** [comment]
@jhorowitz-firedrum :)

**Comment by ghost** [comment]
Thanks @krzysiek1507! :)

**Comment by krzysiek1507** [comment]
Thanks! Could you please release a new version? ;)

**Comment by ghost** [comment]
Sure thing, v1.0.10 published to npm!
Sorry for the delay :)

**Comment by krzysiek1507** [comment]
Thank you! :)

**Pull request merged**
